# Generated by Django 5.0.1 on 2024-01-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_review_rating'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='productimage',
            table='products_ProductImage',
        ),
    ]
